// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCboEV-Mq5MyzuX5ZiOS245Z7u-xZD1jK8',
    appId: '1:593992384993:web:002c191c388ebaf4c2d2a0',
    messagingSenderId: '593992384993',
    projectId: 'mainproject-fb94e',
    authDomain: 'mainproject-fb94e.firebaseapp.com',
    storageBucket: 'mainproject-fb94e.firebasestorage.app',
    measurementId: 'G-3BRMR68V4H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4bt-WQzpU5JVNkMl_-_1ORi701LW6Ims',
    appId: '1:593992384993:android:eda07c630fc445d3c2d2a0',
    messagingSenderId: '593992384993',
    projectId: 'mainproject-fb94e',
    storageBucket: 'mainproject-fb94e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDa4SzxmFfnxINSX-djton0oBbd36m_pOQ',
    appId: '1:593992384993:ios:0c710fe3404f624fc2d2a0',
    messagingSenderId: '593992384993',
    projectId: 'mainproject-fb94e',
    storageBucket: 'mainproject-fb94e.firebasestorage.app',
    iosBundleId: 'com.example.mainproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDa4SzxmFfnxINSX-djton0oBbd36m_pOQ',
    appId: '1:593992384993:ios:0c710fe3404f624fc2d2a0',
    messagingSenderId: '593992384993',
    projectId: 'mainproject-fb94e',
    storageBucket: 'mainproject-fb94e.firebasestorage.app',
    iosBundleId: 'com.example.mainproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCboEV-Mq5MyzuX5ZiOS245Z7u-xZD1jK8',
    appId: '1:593992384993:web:82b2cbdec1fe739dc2d2a0',
    messagingSenderId: '593992384993',
    projectId: 'mainproject-fb94e',
    authDomain: 'mainproject-fb94e.firebaseapp.com',
    storageBucket: 'mainproject-fb94e.firebasestorage.app',
    measurementId: 'G-KVQLV0CMZN',
  );

}